### ISSUE TITLE
Badges needed

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx-mio#2]
Hello @TechWriter-Mayur , can you please add the badges to this repo?

**Comment by TechWriter-Mayur** [comment]
I have added the badges and created the PR #4 for the same.

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Marking this issue Closed and corresponding PR is merged already

**Comment by johnbent** [comment]
Hello @chandradharraval , this is not done.

Here are the badges for this repo:
![image](https://user-images.githubusercontent.com/2047294/165827282-a539d45b-920b-4fc6-87f2-993a05f83b14.png)

It only has the codacy badge. But it should have all the badges like this:
![image](https://user-images.githubusercontent.com/2047294/165827350-480d1c3e-94e7-4ebe-aa73-53df8d8b16ef.png)

**Comment by johnbent** [comment]
I'm reopening

**Comment by cortx-admin** [comment]
> John Bent commented in Jira Server:

Please see github comment:

[https://github.com/Seagate/cortx-mio/issues/2]

This is not fixed yet. Re-opening.

**Comment by nezzzu** [comment]
Reopening as requested by @johnbent.

**Comment by chandradharraval** [comment]
Hi @johnbent,
Have we created another github [1705](https://github.com/Seagate/cortx-motr/issues/1705) for the same issue?

**Comment by swatid-seagate** [comment]
FYI. #1750 is resolved and now codacy badge in the cortx-motr repo is rendering correctly.

**Comment by swatid-seagate** [comment]
This issue resolved. README updated for all the badges. Please check.

**Comment by chandradharraval** [comment]
Hi @swatid-seagate ,
As per above comment from @johnbent, this issue about "cortx-mio" repo. Can you please check badges for the same as per [comment](https://github.com/Seagate/cortx-mio/issues/2#issuecomment-1112558628)

**Comment by swatid-seagate** [comment]
All the badges are added in cortx-mio as suggested. The PR is merged too. Ganesan helped merge the PR. Please do check.

**Comment by nkommuri** [comment]
@johnbent  Can you please close this Github Issue. I don't have permission to close. Thanks

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Marking this Jira Closed based on above comments
