### ISSUE TITLE
License changes needed

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx-mio#3]
@gauravchaudhari02 , when we did the initial license migration, who did that work?  Do we still have those scripts?  Can you please work to update the licenses in all of the source files in this repo to be Apache?

**Comment by gauravchaudhari02** [comment]
@johnbent, I did not work on license migration. But @mukul-seagate11 and @nileshgovande might have an idea about it.

**Comment by mukul-seagate11** [comment]
@pujamudaliar, as the License changes was performed by you earlier so please take care & update the same as requested?

**Comment by nileshgovande** [comment]
I did not work on cortx-mio license. I did it only in s3

**Comment by chandradharraval** [comment]
@johnbent - Is this ticket still valid?

**Comment by chandradharraval** [comment]
@mukul-seagate11 - Can you check above comments from @johnbent and suggest next steps?

**Comment by chandradharraval** [comment]
Hi @mukul-seagate11 ,
I plan to close this issue as there are no updates. Can you please confirm if we are ok?

**Comment by cortx-admin** [comment]
> Mukul Malhotra commented in Jira Server:

[~530903], yes to correct the headers in the license file, Motr team have to raise a PR and once its merge then the this request can be closed

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
